workflows:
  react-native-ios:
    name: React Native iOS Workflow for UAWauto
    environment:
      vars:
        XCODE_WORKSPACE: "ios/UAWauto.xcworkspace"
        XCODE_SCHEME: "UAWauto"
      node: 18.16.0
      xcode: latest
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
      - name: Build iOS app
        script: |
          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            -derivedDataPath build
    artifacts:
      - ios/build/Build/Products/Release-iphoneos/*.app
    publishing:
      email:
        recipients:
          - piyush.70600@gmail.com
